/**
 * Temporary Prisma type definitions
 * These types should be generated by `prisma generate`
 * This file provides fallback types when Prisma client cannot be regenerated
 */

declare module '@prisma/client' {
  export enum UserRole {
    ADMIN = 'ADMIN',
    USER = 'USER',
  }

  export enum AIProvider {
    OPENAI = 'OPENAI',
    ANTHROPIC = 'ANTHROPIC',
    GOOGLE = 'GOOGLE',
    COHERE = 'COHERE',
    HUGGINGFACE = 'HUGGINGFACE',
  }

  export enum MessageRole {
    USER = 'USER',
    ASSISTANT = 'ASSISTANT',
    SYSTEM = 'SYSTEM',
    FUNCTION = 'FUNCTION',
  }
}
